### ISSUE TITLE
dynamic way of detecting brew

### ISSUE THREAD

**Issue by HaniAlshikh** [munkireport/homebrew#1]
Hi,

have you experimented with the local installation of Homebrew, where the user is not an admin and therefore can't install homebrew in /usr/local? i just finished writing/modifying a homebrew installer, that checks if the user is admin or not and depending on the result either install brew in /usr/local or ~/.brew.

I took a lock at your script (here and in homebrew_info) and noticed that you only check for this path ```/usr/local/bin/brew``` and i was wondering if there is any reason why making it a bit more dynamic might be a problem for example

```[[ -f  $(sudo -i -u $ConsoleUser command -v brew) ]]```

should i test this and make a PR?

**Comment by tuxudo** [comment]
Resolved with PR #2
